name: Checks

on:
  pull_request:

jobs:
  Golangci-Lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.23"

      - name: Install dependencies
        run: |
          go version
          go install github.com/golangci/golangci-lint/v2/cmd/golangci-lint@v2.5.0

      - name: Run golangci-lint
        run: |
          golangci-lint run builder/...

  Go-Fmt:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.23"

      - name: Run fmt
        run: |
          gofmt_files=$(gofmt -l builder)
          if [[ -n ${gofmt_files} ]]; then
              echo 'gofmt needs running on the following files:'
              echo "${gofmt_files}"
              exit 1
          fi
          exit 0
