name: Nightly Acceptance
on:
  schedule:
    - cron: '0 5 * * *' # UTC

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-go@v6
        with:
          go-version: '^1.25'
      - run: make test
        env:
          PACKER_ACC: ${{ secrets.PACKER_ACC }}
          VULTR_API_KEY: ${{ secrets.VULTR_API_KEY }}

  notify:
    name: Mattermost Notification
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: mattermost/action-mattermost-notify@2.0.0
        with:
          MATTERMOST_WEBHOOK_URL: ${{ secrets.MATTERMOST_WEBHOOK_URL }}
          MATTERMOST_USERNAME: ${{ secrets.MATTERMOST_USERNAME }}
          MATTERMOST_ICON_URL: ${{ secrets.MATTERMOST_ICON }}
          TEXT: "Packer Nightly Acceptance Job Status: ${{ needs.build.result }}"